<Project>
  <ItemGroup>
    <!-- Serilog -->
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <!-- Microsoft.Extensions -->
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5" />
    <!-- EntityFrameworkCore -->
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5" />
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
  </ItemGroup>
</Project>