name: Publish.Nuget.All

on:
  workflow_dispatch:
    
  release:
    types:
      - published
  
permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.x.x'

      - name: Restore Dependencies
        working-directory: ./src
        run: dotnet restore Nixon.Extensions.slnx

      - name: Build Solution
        working-directory: ./src
        run: dotnet build Nixon.Extensions.slnx -c Release --no-restore

      - name: Run Tests
        working-directory: ./src
        run: dotnet test Nixon.Extensions.slnx -c Release --no-build

      - name: Pack Packages
        working-directory: ./src
        run: |         
          dotnet pack Nixon.Extensions.Configuration/Nixon.Extensions.Configuration.csproj              -c Release --no-build -o ./dist
          dotnet pack Nixon.Extensions.Serilog.AspNetCore/Nixon.Extensions.Serilog.AspNetCore.csproj    -c Release --no-build -o ./dist
          dotnet pack Nixon.Extensions.EntityFrameworkCore/Nixon.Extensions.EntityFrameworkCore.csproj  -c Release --no-build -o ./dist
          dotnet pack Nixon.Extensions.Hosting.Jobs/Nixon.Extensions.Hosting.Jobs.csproj                -c Release --no-build -o ./dist
          
          dotnet pack Nixon.Extensions.OpenIddict/Nixon.Extensions.OpenIddict.csproj                                          -c Release --no-build -o ./dist
          dotnet pack Nixon.Extensions.OpenIddict.EntityFrameworkCore/Nixon.Extensions.OpenIddict.EntityFrameworkCore.csproj  -c Release --no-build -o ./dist

      - name: NuGet OIDC Login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push to NuGet.org
        working-directory: ./src
        run: |
          dotnet nuget push "./dist/*.nupkg" \
            --api-key ${{ steps.login.outputs.NUGET_API_KEY }}  \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate